### ISSUE TITLE
Cannot work after install it by follow guide-win7 64bit

### ISSUE THREAD

**Issue by bobdog1986** [jakubgarfield/Bonobo-Git-Server#399]
Hello everyone!
After install it by following the guide, it doesnot work! My system is win7,and already run a bugzilla service.So,
If I view the web page, it show error like this:
![image](https://cloud.githubusercontent.com/assets/9330555/12254302/f6c1edd8-b921-11e5-87be-dbaa88d47bfb.png)
My setting is:
![image](https://cloud.githubusercontent.com/assets/9330555/12254362/8ba69444-b922-11e5-94a7-f62c7f5d8403.png)
Anonymous Authentication is enabled , But why I cannot visit server?

**Comment by bobdog1986** [comment]
Default documents setting is:
![image](https://cloud.githubusercontent.com/assets/9330555/12254481/167405b0-b924-11e5-8721-9883ca267087.png)

**Comment by RedX2501** [comment]
Please go to your web.config and change 
```
    <customErrors mode="On" defaultRedirect="Home/Error" />
```
to 
```
    <customErrors mode="Off" defaultRedirect="Home/Error" />
```

and tell us which error you get.

**Comment by bobdog1986** [comment]
Hello RedX2501 , it seems like miss the SqlLite module. My Brower is Chrome 47.0.2526.106 (64-bit) . it doesnot work with IE either. Here is the message:

Server Error in '/Bonobo.Git.Server' Application.

Unable to load DLL 'SQLite.Interop.dll': 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)]
   System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op) +0
   System.Data.SQLite.SQLite3.StaticIsInitialized() +123
   System.Data.SQLite.SQLiteLog.Initialize() +32
   System.Data.SQLite.SQLiteFactory..cctor() +119

[TypeInitializationException: The type initializer for 'System.Data.SQLite.SQLiteFactory' threw an exception.]

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeFieldHandle.GetValue(RtFieldInfo field, Object instance, RuntimeType fieldType, RuntimeType declaringType, Boolean& domainInitialized) +0
   System.Reflection.RtFieldInfo.UnsafeGetValue(Object obj) +158
   System.Reflection.RtFieldInfo.GetValue(Object obj) +29
   System.Data.Common.DbProviderFactories.GetFactory(DataRow providerRow) +269
   System.Data.Entity.Infrastructure.DependencyResolution.DefaultProviderFactoryResolver.GetService(Type type, Object key, Func`3 handleFailedLookup) +94
   System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) +84
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +80
   System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source, Func`2 predicate) +200
   System.Data.Entity.Infrastructure.DependencyResolution.RootDependencyResolver.GetService(Type type, Object key) +86
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +80
   System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source, Func`2 predicate) +116
   System.Data.Entity.Infrastructure.DependencyResolution.CompositeResolver`2.GetService(Type type, Object key) +71
   System.Data.Entity.Infrastructure.DependencyResolution.DbDependencyResolverExtensions.GetService(IDbDependencyResolver resolver, Object key) +105
   System.Data.Entity.Internal.LazyInternalConnection.CreateConnectionFromProviderName(String providerInvariantName) +69
   System.Data.Entity.Internal.LazyInternalConnection.InitializeFromConnectionStringSetting(ConnectionStringSettings appConfigConnection) +144
   System.Data.Entity.Internal.LazyInternalConnection.TryInitializeFromAppConfig(String name, AppConfig config) +39
   System.Data.Entity.Internal.LazyInternalConnection.Initialize() +160
   System.Data.Entity.Internal.LazyInternalConnection.get_Connection() +16
   Bonobo.Git.Server.Data.Update.AutomaticUpdater.UpdateDatabase() +118
   Bonobo.Git.Server.MvcApplication.Application_Start() +121

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +544
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +186
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +402
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +343

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +579
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +112
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +712

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0

**Comment by bobdog1986** [comment]
Whick Dir should I copy that dll file to? Or need install a package for GAC reason?
I can see 3 dll files in the Bonodo.Git.Server\bin folder:
System.Data.SQLite.dll
System.Data.SQLite.EF6.dll
System.Data.SQLite.Linq.dll

**Comment by RedX2501** [comment]
It should be fixed in package 5.1.1 i reported this error in #393.

**Comment by bobdog1986** [comment]
Thank you!
I try to google it on web and had try follows:
1. Reinstall Microsoft Visual C++ 2010 SP1 Redistributable Package (x86)
2. Reg x64 version 'SQLite.Interop.dll' to c:\windows\system32
3. copy to bonobo.git.server\bin folder

But it still not work.

**Comment by RedX2501** [comment]
So you redownloaded 5.1.1 and it still did not work?

There should be a x64 and x86 folder in your bin folder. Are they there?

**Comment by bobdog1986** [comment]
In 5.1.0 version zip, there is no x64 or x86 folder. I am downloading 5.1.1 zip now , hope can work well. 
My visual studio 2015 ce lack web develop tool , so I cannot build this project. I am updating my visual studio now.
Thanks for your help. If new 5.1.1 version work ,I will update and close this issue.

**Comment by bobdog1986** [comment]
New release 5.1.1 close this issue. Thanks to you help, Redx.
