### ISSUE TITLE
Bonobo 5.2.0 and Active Directory

### ISSUE THREAD

**Issue by mrloddo** [jakubgarfield/Bonobo-Git-Server#558]
Hi all,
I've installed Bonobo v5.2 with Windows authentication and Internal Membership (it's complex to manage groups in my organization).

My principal issue is that Bonobo doesn't create any AD users on DB and I'm unable to logon. If I switch in cookie authentication I can only view Admin user.

Thanks in advance.
Marco

**Comment by willdean** [comment]
Internal membership means the list of users come from Bonobo's database.   You can only make this work with Windows authentication if you (manually) arrange to have users in Bonobo's database which match the Windows users.

**Comment by mrloddo** [comment]
So I did a mistake considering the AD User would created in the Bonobo's database. Just because in the previous version (at least 3.6) it was the expected behavior. 

I have to presume I cannot use the following flags together without touch the Bonobo's database:
<add key="AuthenticationProvider" value="Windows" />
<add key="MembershipService" value="Internal" />

**Comment by RedX2501** [comment]
I do have the same arrangement and it works fine for me.

**Comment by mrloddo** [comment]
So this kind of configuration has to work.
is there a way to trace Bonobo code during the logon step? You have to consider that I've already tried to use WinAuth + AD Membership and the user are created correctly. But I don't have this configuration.

**Comment by sedotakj** [comment]
I'm having thew same problem. No amount of config changes let me use AD users. 
What should be the Web Site's IIS Authentication? 
Should Basic Authentication be enabled? Should Windows Authentication be Enabled?
Does the AppPool need to run as any special user?
What are the meanings of the config entries ActiveDirectoryMemberGroupName, ActiveDirectoryTeamMapping and ActiveDirectoryRoleMapping?

**Comment by RobertMcCoy** [comment]
Sedotakj, did you ever get this working? I'm getting stuck on the basic authentication. It just keeps prompting me for my username/password every time I go to the site, and it never takes any type of input as valid. Getting pretty frustrated with this, and I think I might find an alternative if I can't find someone who has gotten this working yet.

**Comment by willdean** [comment]
@RobertMcCoy Can you say which version of bonobo you're running and post the relevant bit of your web.config?

**Comment by RobertMcCoy** [comment]
@willdean I'm running v. 6.0.0.433

`
    <add key="AuthenticationProvider" value="Windows" />
    <add key="ImportWindowsAuthUsersAsAdmin" value="false" />

    
    
    <add key="MembershipService" value="ActiveDirectory" />
    <add key="ActiveDirectoryDefaultDomain" value="[Hidden For Github Issue]" />
    <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />
    <add key="ActiveDirectoryMemberGroupName" value="MIS" />
    <add key="ActiveDirectoryTeamMapping" value="GIS=GitGIS,Server=GitServerAdmins,Network=GitNetworkAdmins,SoftwareDev=GitAppDevs,UNIX=GitUNIX,WebDev=GitWebDevs" />
    <add key="ActiveDirectoryRoleMapping" value="Administrator=GitAdmins" />`

I have Basic, Anonymous, and Windows Authentication Enabled (I have tried every combination of these three). I have the ASP.NET v4.0 DefaultAppPool set to be running as a NetworkService, and it's Framework version is v4.0.30319. 

Everytime I go to the site that is hosted on a virtual server we are running, it prompts me to enter my login, and no combination of username, domain\username, username@domain appears to work, and it just prompts me to enter my credentials again when I submit the current credentials.

**Comment by willdean** [comment]
@RobertMcCoy Sorry for such a slow reply.  If you're still happy to look at this, could you go to http://<myserver>/Home/Diagnostics and post the result here (have a look if there's any bits you want to redact first).

You'll need to do this on the server, as it won't serve this page remotely.

**Comment by RobertMcCoy** [comment]
```
Web.Config AppSettings
--AppSettings.webpages:Enabled: 'false'
--AppSettings.ClientValidationEnabled: 'true'
--AppSettings.UnobtrusiveJavaScriptEnabled: 'true'
--AppSettings.UserConfiguration: '~\App_Data\config.xml'
--AppSettings.DefaultRepositoriesDirectory: '~\App_Data\Repositories'
--AppSettings.GitPath: '~\App_Data\Git\git.exe'
--AppSettings.GitHomePath: '~\App_Data'
--AppSettings.RecoveryDataPath: '~\App_Data\Recovery'
--AppSettings.AuthenticationProvider: 'Windows'
--AppSettings.ImportWindowsAuthUsersAsAdmin: 'false'
--AppSettings.MembershipService: 'ActiveDirectory'
--AppSettings.ActiveDirectoryDefaultDomain: '#redacted'
--AppSettings.ActiveDirectoryBackendPath: '~\App_Data\ADBackend'
--AppSettings.ActiveDirectoryMemberGroupName: 'MIS'
--AppSettings.ActiveDirectoryTeamMapping: 'Test=MIS'
--AppSettings.ActiveDirectoryRoleMapping: 'Administrator=MIS'
User Configuration:
--User config file: 'C:\inetpub\wwwroot\Bonobo\App_Data\config.xml'
--User config readable: OK
--User config saveable: OK
--User config folder: Exists, 6 files, 9 entries, writeable
Repo Directory
--Configured repo path: '~\App_Data\Repositories'
--Effective repo path: 'C:\inetpub\wwwroot\Bonobo\App_Data\Repositories'
--Repo dir: Exists, 1 files, 1 entries, writeable
Git Exe
--Git path: 'C:\inetpub\wwwroot\Bonobo\App_Data\Git\git.exe'
--Git.exe exists: OK
Federated Authentication
--Not Enabled: 
Active Directory
--Backend folder exists: OK
--Backend folder: Exists, 0 files, 4 entries, writeable
--User count: 0
AD Teams
AD Roles
Internal Membership
--Not Enabled
**********************************************************************************
Exception Log
--LogFileName: : C:\inetpub\wwwroot\Bonobo\App_Data\Bonobo.Git.Server.Errors.log
--Log File total length: 39449
--Starting log dump from : 29449
r(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at Bonobo.Git.Server.Data.ADBackend.UpdateTeams()
w3wp.exe Error: 0 : 09/28/2016 11:24:10: ADBackend Exception: System.DirectoryServices.DirectoryServicesCOMException (0x80072020): An operations error occurred.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInitNoContainer()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoDomainInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at Bonobo.Git.Server.Data.ADBackend.UpdateTeams()
w3wp.exe Error: 0 : 09/28/2016 11:24:10: ADBackend Exception: System.DirectoryServices.DirectoryServicesCOMException (0x80072020): An operations error occurred.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInitNoContainer()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoDomainInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at Bonobo.Git.Server.Data.ADBackend.UpdateTeams()
w3wp.exe Error: 0 : 09/28/2016 11:24:10: ADBackend Exception: System.DirectoryServices.DirectoryServicesCOMException (0x80072020): An operations error occurred.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInitNoContainer()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoDomainInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at Bonobo.Git.Server.Data.ADBackend.UpdateRoles()
   at Bonobo.Git.Server.Data.ADBackend.Update(Object state)
Native library pre-loader is trying to load native SQLite library "C:\inetpub\wwwroot\Bonobo\bin\x64\SQLite.Interop.dll"...
w3wp.exe Error: 0 : 09/28/2016 11:25:51: ADBackend Exception: System.DirectoryServices.DirectoryServicesCOMException (0x80072020): An operations error occurred.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInitNoContainer()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoDomainInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at Bonobo.Git.Server.Data.ADBackend.UpdateUsers()
w3wp.exe Error: 0 : 09/28/2016 11:25:51: ADBackend Exception: System.DirectoryServices.DirectoryServicesCOMException (0x80072020): An operations error occurred.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInitNoContainer()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoDomainInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at Bonobo.Git.Server.Data.ADBackend.UpdateTeams()
w3wp.exe Error: 0 : 09/28/2016 11:25:51: ADBackend Exception: System.DirectoryServices.DirectoryServicesCOMException (0x80072020): An operations error occurred.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInitNoContainer()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoDomainInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at Bonobo.Git.Server.Data.ADBackend.UpdateRoles()
   at Bonobo.Git.Server.Data.ADBackend.Update(Object state)



```

My running theory is it has no default LDAP credentials...so how could it ever verify that a user exists or not if it cannot see information in the first place? But, I'm not a server/network admin, so I have no way to verify if that's truly the issue, as the only thing all of this logging suggests is that there are no users being generated from AD (which makes me think the above)

**Comment by willdean** [comment]
Thanks very much for this - does this SO thread cast any light:

http://stackoverflow.com/questions/7285503/active-directory-com-exception-an-operations-error-occured-0x80072020/19036826#19036826

Perhaps this is an issue with the user that IIS is using for Bonobo?

**Comment by RobertMcCoy** [comment]
Potentially. I believe I have full administrator rights on the server on which the website resides. I will speak with one of our server guys on getting the administrator logon for the server and see if that impacts performance.

**Comment by jzizmor** [comment]
I'm trying for the same setup as @mrloddo , do either you or @RedX2501 know how to edit the users in the Bonobo database?

**Comment by larshg** [comment]
@mrloddo, @sedotakj and @RobertMcCoy can you please try the new 6.1 and report back again?

**Comment by RobertMcCoy** [comment]
I won't be able to sadly, as I am no longer with the company in which I was trying to set this up on, and therefore don't have access to the AD setup there.

**Comment by willdean** [comment]
@RobertMcCoy No worries - thanks for the help previously - good luck in the new job...

**Comment by larshg** [comment]
Closing as the original issue should be fixed in recent PRs.

**Comment by JMoorhouse07** [comment]
I'm aware this issue has been closed. However I'd like to note that I too experienced RobertMcCoy's issue--and that I've solved it.

Changing the MembershipService from Internal to ActiveDirectory is necessary for use of AD, obviously. However, there is no need to change the AuthenticationProvidor--which is what I'm assuming the above poster did. See below:

    <add key="AuthenticationProvider" value="Cookies" />
    
    <add key="ImportWindowsAuthUsersAsAdmin" value="false" />
    
    
    <add key="MembershipService" value="ActiveDirectory" />
    <add key="ActiveDirectoryDefaultDomain" value="[myactivedirectory].local" />
    <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />
    <add key="ActiveDirectoryMemberGroupName" value="[mygituser]" />
    <add key="ActiveDirectoryRoleMapping" value="Administrator=[mygituser]" />

Note that I've configured our server to only have one user that's both user and administrator.

**Comment by AspenForester** [comment]
We're seeing the same behavior as JMoorhouse07.  When we switched *back* to  AuthenticationProvider = "Cookies", but left the other AD authentication-related settings in place, AD authentication started working.

**Comment by djscott00** [comment]
I'm in the process of setting up Bonobo, and I can also confirm that I needed to change AuthenticationProvider to "Cookies" as well to get AD authentication working correctly.

In my logs, I could see that users were correctly authenticating their credentials, but it was still the same login screen that would appear without error. Once I changed to "Cookies" it started working right away.

Thanks for the tip JMoorhouse07.

**Comment by FlashGordon7** [comment]
We had the same problem.
So also a thanks for the tip JMoorhouse07

**Comment by MixanM** [comment]
Good afternoon, faced the same problem, but I have questions: why does Bonobo need a domain administrator? According to the log file. "```
 2022-06-15 09:15:26.948 +05:00 [Information] Searching for group "mmy_srv" in domain "gt.gr.local"
2022-06-15 09:15:27.089 +05:00 [Error] AD: Failed to update role "Administrator"
System.ArgumentException: Could not find principal group: mmy_srv
   at Bonobo.Git.Server.Helpers.ADHelper.GetPrincipalGroup(String name, GroupPrincipal& group)
   in Bonobo.Git.Server.Data.ADBackend.UpdateRoles()"
```. I think my mistake is related to this. Can anyone help with setting up Bononbo?
