### ISSUE TITLE
windows authentication doesn't work

### ISSUE THREAD

**Issue by marko033** [jakubgarfield/Bonobo-Git-Server#780]
Hi, I have a problem with Windows authentication.
i was using 6.2.1 everything was ok.
I made upgrade to 6.3.0 and I start have problem with Windows authentication.
When I go to Bonobo-Git-Server site browser ask Username and Password.
I use my username and password but it is bad and ask again and again.
Where can by a problem?
Should I set up something on IIS ?

Thak You.

**Comment by CatStarwind** [comment]
The best thing to do right now is to rollback to 6.2.1 as it is a known issue. #775  #743

**Comment by marko033** [comment]
I was trying but I have this problem now also on 6.2.1.

**Comment by CatStarwind** [comment]
I updated my PR #763 to try to fix this.

**Comment by marko033** [comment]
I tried but did not help.
Can I have some bad settings on IIS?
Is there some addition setting for Windows Authentication for IIS?

**Comment by CatStarwind** [comment]
Make sure the only Authentication enabled is `Anonymous Authentication` in IIS. (from the website: https://bonobogitserver.com/resources/img/installation/iis_authentication_forms.png)

You might also want to check that you have Basic and Windows Authentication installed.

**Comment by marko033** [comment]
Yes I have only Anonymous Authentication enabled.
How I wrote it is work on 6.2.1 version then I upgrade to 6.3.0 then stop Windows Authentication work. Ok I have backup previous working version so I restore it but it did not help. Windows Authentication still not working.

**Comment by mu88** [comment]
I have exactly the same issue, but changing the resource `/Logon/` to `/WindowsLogin/` works. It is a workaround, but at least it works

**Comment by LarsOAndersen** [comment]
Hi. i am using 6.3 and when i use windows authentication, it actual look my credentials up. but when it is done checking it just clears the forms and does not login. somehow it cannot find out to login with administrative rights ?? any suggestions.

**Comment by ChrisSorel** [comment]
Having this same issue. Is there any fix?
